In [4]:
import numpy as np

array = np.array([2,3,5,6,4,4,3])
print(array[3])
array.dtype

6


dtype('int32')

## arange function

In [5]:
import numpy as np

array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


## arange with 3 difference

In [6]:
import numpy as np

array = np.arange(0,15,3)
print(array.dtype)
print(array)

int32
[ 0  3  6  9 12]


## linearspace 

In [7]:
import numpy as np
# compiler will find that numbers which having same difference
array = np.linspace(0,10,5)
print(array.dtype)
print(array)

float64
[ 0.   2.5  5.   7.5 10. ]


## ones and zeros with different types

In [8]:
import numpy as np

array = np.ones(5, dtype = np.int8)
print(array.dtype)
print(array)

int8
[1 1 1 1 1]


In [9]:
import numpy as np

array = np.zeros(5, dtype = np.int8)
print(array.dtype)
print(array)

int8
[0 0 0 0 0]


In [10]:
import numpy as np

array = np.zeros(5, dtype = np.float64)
print(array.dtype)
print(array)

float64
[0. 0. 0. 0. 0.]


In [11]:
import numpy as np

array = np.ones((5,5), dtype = np.float64)
print(array.dtype)
print(array)

float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
import numpy as np

array = np.empty((5,5), dtype = np.float64)
print(array.dtype)
print(array)

float64
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## Reshape

In [13]:
import numpy as np

array = np.arange(0,24)
array = array.reshape(2,3,4)
print(array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
import numpy as np

array = np.arange(0,24)
array = array.reshape(6,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [15]:
import numpy as np

food = np.array(['ahmed',34])
print(food)

['ahmed' '34']


In [19]:
import numpy as np
import pandas as pd
array = np.arange(0,24)
array = array.reshape(2,3,4)
for i in range(0,5):
    print(array)
    print("\n\n")

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



